export const APP_LOADING = "APP_LOADING";
export const USER_LOGIN = "USER_LOGIN";
export const USER_REGISTER = "USER_REGISTER";
export const LOGOUT = 'LOGOUT';
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const REFRESH_TOKEN = 'REFRESH_TOKEN';